website/website/akuns/urls.py
from django.conf.urls import url
from . import views

app_name = "akuns"

urlpatterns = [
    url(r"^register/$", views.register, name = "signup"),
    url(r"^login/$", views.sign_in, name = "signin"),
    url(r"^logout/$", views.logout_view, name = "logout"),
]

website/website/profiles/urls.py
from django.conf.urls import url
from . import views

app_name = "profiles"

urlpatterns = [
    url(r"^account_status/$", views.index, name = "account_status"),
    url(r"^money_transfer/", views.money_transfer, name = "money_transfer"),
    url(r"^loan_app/$", views.loan, name = "loan_app"),
    url(r"settings/$", views.settings, name = "settings"),
    url(r"edit_details/", views.edit_details, name = "edit_details"),
    url(r"delete_account/$", views.delete_account, name = "delete_account")
]

website/website/website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="home"),
    url(r'^akuns/', include("akuns.urls")),
    url(r'^profile/', include("profiles.urls")),
    url(r'^admins/', include("admins.urls"))
]

website/website/profiles/models.py
from django.db import models
import datetime

class Customer (models.Model): 
    name = models.CharField(max_length = 50, default = None)
    email = models.EmailField(default = None)
    address = models.CharField(max_length=50, default=None)
    phone = models.IntegerField (default=0)
    user_name = models.CharField(max_length = 150, default = None)

class Status (models.Model):
    account_number = models.IntegerField(default=0)
    balance = models.IntegerField()
    user_name = models.CharField(max_length = 150, default = None)

class MoneyTransfer(models.Model):
    Masukan_Nama_Penyetor = models.CharField(max_length = 150, default = None)
    Masukan_No_Akuns_Tujuan = models.IntegerField()
    Masukan_Jumlah_Uang_Dalam_USD = models.IntegerField()

website/website/akuns/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','first_name', 'last_name','password1', 'password2', )

website/website/profiles/forms.py
from django import forms
from . import models

class CustomerForm (forms.ModelForm):
    # class to store all the model form fields from models.py
    class Meta:
        model = models.Customer
        fields = ["name", "email", "address", "phone"]

class MoneyTransferForm (forms.ModelForm):
    class Meta:
        model = models.MoneyTransfer
        fields = [
            "Masukan_Nama_Penyetor",
            "Masukan_No_Akuns_Tujuan", 
            "Masukan_Jumlah_Uang_Dalam_USD"
        ]

website/website/akuns/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
from .forms import SignUpForm

def register(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            return redirect("akuns:signin")
    else:
        form = SignUpForm()
    return render(request, "akuns/create_account.html", {"form": form})

def sign_in(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("profiles:account_status")
    else:
        form = AuthenticationForm()
    return render(request, "akuns/sign_in.html", {"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("akuns:signin")

website/website/profiles/views.py
from django.shortcuts import render, redirect
from . import forms
from . import models
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from profiles.models import Status 
import random
from django.contrib import messages
from django.contrib.auth.models import User

def randomGen():
    # return a 11 digit random number
    return int(random.uniform(10000000000, 99999999999))

def index(request):
    try:
        curr_user = Status.objects.get(user_name=request.user) # getting details of current user
    except:
        # if no details exist (new user), create new details
        curr_user = Status()
        curr_user.account_number = randomGen() # random account number for every new user
        curr_user.balance = 0
        curr_user.user_name = request.user
        curr_user.save()
    return render(request, "profiles/profile.html", {"curr_user": curr_user})

def money_transfer(request):
    if request.method == "POST":
        form = forms.MoneyTransferForm(request.POST)
        if form.is_valid():
            form.save()
        
            curr_user = models.MoneyTransfer.objects.get(Masukan_Nama_Penyetor=request.user)
            dest_user_acc_num = curr_user.Masukan_No_Akuns_Tujuan

            temp = curr_user # NOTE: Delete this instance once money transfer is done
            
            dest_user = models.Status.objects.get(account_number=dest_user_acc_num) # FIELD 1
            transfer_amount = curr_user.Masukan_Jumlah_Uang_Dalam_USD # FIELD 2
            curr_user = models.Status.objects.get(user_name=request.user) # FIELD 3

            # Now transfer the money!
            curr_user.balance = curr_user.balance - transfer_amount
            dest_user.balance = dest_user.balance + transfer_amount

            # Save the changes before redirecting
            curr_user.save()
            dest_user.save()

            temp.delete() # NOTE: Now deleting the instance for future money transactions

        return redirect("profiles/profile.html")
    else:
        form = forms.MoneyTransferForm()
    return render(request, "profiles/money_transfer.html", {"form": form})

def loan(request):
    return render(request, "profiles/loans.html")

def settings(request):
    return render(request, "profiles/settings.html")

def edit_details(request):
    if request.method == "POST":
        # POST actions for CustomerForms
        try:
            curr_user = models.Customer.objects.get(user_name=request.user)
            form = forms.CustomerForm(request.POST, instance=curr_user)
            if form.is_valid():
                form.save()
        except:
            form = forms.CustomerForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user_name = request.user
                form.save()  
        
        # POST actions for Password change
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error below.')

        return redirect("profiles/edit_details.html")
    
    else: # GET actions
        try:
            curr_user = models.Customer.objects.get(user_name=request.user)
            form1 = forms.CustomerForm(instance=curr_user) # basic details
        except:
            form1 = forms.CustomerForm()


        # change password
        form3 = PasswordChangeForm(request.user)

        dici = {"form1": form1, "form3": form3}
        return render(request, "profiles/edit_details.html", dici)

def delete_account(request):
    try:
        u = User.objects.get(username = akunusername)
        u.delete()
        messages.success(request, "The user is deleted")
    except User.DoesNotExist:
        messages.error(request, "User doesnot exist")    
        return render(request, 'index.html')

    except Exception as e: 
        return render(request, 'index.html')
    return render(request, "index.html")

website/website/website/views.py
from django.shortcuts import render

def index(request):
    return render(request, "index.html")

website/website/akuns/templates/akuns/create_account.html
{% extends 'base_layout.html' %}
{%load static%}
{% block stylecontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Slabo+27px');
        
        body {
            background-color: skyblue;
        }
        h2 {
            font-family: 'Slabo 27px';
            border-bottom: 1px solid black;
            font-weight: 900;
        }
        form ul {
            list-style: none;
        }
    </style>

            
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <link rel="stylesheet" href="{%static "style_createakun.css"%}">
{% endblock %}

        
{% block bodycontent %}    
<div class="container">
    <h1>Create New Akun</h1>
    <form  action="/akuns/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button>Create New Account</button>
    </form>
        
        <section>
            <input type="checkbox" required> 
            <small>By clicking "Create account" you agree to our  
                <a href="#">Terms and Conditions</a>.</small>
        </section>

    <br>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".active").removeClass("active");
        $("#nav-create").addClass("active");

        $(".helptext").html("");

        var input_text = $("input[type=text]");
        input_text.addClass("form-control");

        var input_pass = $("input[type=password]");
        input_pass.addClass("form-control");

        $("form ul li").addClass("btn btn-danger");

        // var labels = $("label");

        // labels.addClass("col");
        // input_text.addClass("col")
        // input_pass.addClass("col");
    </script>
{% endblock %}

website/website/akuns/templates/akuns/sign_in.html
{% extends 'base_layout.html' %}
{% load static %}
{% block stylecontent %}
    <style>
        body {
            background-color: aliceblue
        }
        
        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }    
    </style>
    <link rel="stylesheet" href="{%static "style_login.css"%}">
{% endblock %}


{% block bodycontent%}
{% csrf_token %}
    <div class="container">
        <h1>Login</h1>
        <form action="/akuns/login/" method="post">
            {% csrf_token %}
            {{ form }}
            <button>Log in</button>
        </form>
        <br>
        <small class="row">
            <a href="{% url 'akuns:signup' %}" class="col text-right">Create New Account</a>
        </small>
    </div>     
{% endblock %}

{% block scriptcontent %}
    <script>
        $( ".input" ).focusin(function() {
        $( this ).find( "span" ).animate({"opacity":"0"}, 200);
        });

        $( ".input" ).focusout(function() {
        $( this ).find( "span" ).animate({"opacity":"1"}, 300);
        }); 
    </script>
{% endblock %}

website/website/profiles/templates/profiles/delete_account.html
{% extends 'profiles/profile_base_layout.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        .g-recaptcha {
            width: 50px;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
    
    <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

{% block bodycontent %}
    <section id="welcome_post" class="col-9">   
        <h3 style="font-weight: 300;" >Deleting the account means:</h3>
        <ul type="square">
            <li>Ini Akan Menghapus Akun Anda Secara Permanent (jadi <a href="{% url 'profiles:money_transfer' %}">transfer uang anda</a> ke akun lain). </li>
        </ul>
        
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#delete" >
            Delete Akun
        </button>

        <!-- Modal -->
        <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="delete" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form>
                    <div class="modal-body">
                        Enter password to confirm deletion
                        <input type="password" class="form-control" required>
                        <br>
                        Prove you are a human
                        <div class="g-recaptcha" data-sitekey="6Ld_qjQUAAAAADjv2scrqpvXK4OrBZALRJFMANpP"></div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete my account</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>
        
        
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#delete").addClass("current");
    </script>
{% endblock %}

website/website/profiles/templates/profiles/edit_details.html
{% extends 'profiles/profile_base_layout.html' %}

{% block headcontent %}
        <style>
            @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
            
            body {
                background-color: floralwhite;
            }
            h2 {
                font-family: "PT Serif";
            }

            #side_panel
            {
                font-size: 16px;
                font-family: "Titillium Web";
                background-color: rgb(57, 74, 170);
                margin-top: -7px;
                margin-left: -10px;
                height: 540px;
                overflow-x: auto;
                overflow-y: auto;
            }
            
            .side {
                color: aliceblue;
            }
            .side:hover {
                color: mediumaquamarine;
            }
            .warning {
                color: yellow;
            }
            .danger {
                color: #FF8723;
                font-weight: 900;
            }
            .current {
                border: 1px solid;
                padding: 3px;
            }
            .curr_bal {
                font-family: "Cinzel";
                font-weight: 600;
            }
            
            #side_panel::-webkit-scrollbar {
                width: 7px;
            }
            #side_panel::-webkit-scrollbar:hover {
                width: 12px;
            }
            #side_panel::-webkit-scrollbar-track {
                -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
                border-radius: 10px;
            }
            ::-webkit-scrollbar-thumb {
                border-radius: 10px;
                -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
            }
        </style>
        
        <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

{% block bodycontent %}
    <section id="welcome_post" class="col-9">                
        <h4 style="font-weight: 300;" >
            Silakan Jika Ingin Memperbarui Identitas Diri Anda
        </h4>
        <br>
        
        <!-- EDIT BASIC DETAILS -->
        <a href="#basic" class="btn btn-primary btn-block" data-toggle="modal" data-target="#basic">Edit basic</a>
        <div class="modal fade" id="basic" tabindex="-1" role="dialog" aria-labelledby="basic" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit basic details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{ url 'profiles:edit_details' }" method="post" enctype="multipart/form-data" id="basic-form">
                    <div class="modal-body">
                       

                        {% csrf_token %}
                        {{ form1 }}
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Edit details</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>
        
        
        (Nama, Email , Alamat , No Telephon)
        <br> <br>
        
        <!-- EDIT ACCOUNT DETAILS -->
        <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#account">Edit account details</button> 
        <div class="modal fade" id="account" tabindex="-1" role="dialog" aria-labelledby="account" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit account type</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    Account type: <br>
                    <input type="radio" checked> Savings
                    <br>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
                </div>
                
            </div>
            </div>
        </div>
        (Account type)
        <br> <br>
        
        <!-- EDIT PASSWORD -->
        <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#password">Edit password</button>
        <div class="modal fade" id="password" tabindex="-1" role="dialog" aria-labelledby="password" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form>
                    <div class="modal-body">
                        
                        {% csrf_token %}
                        {{ form3 }}
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Update password</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>    
        
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#details").addClass("current");

        $("input").addClass("form-control");
        $("input[type=radio]").removeClass("form-control");
    </script>
{% endblock %}

website/website/profiles/templates/profiles/loans.html
{% extends 'profiles/profile_base_layout.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
{% endblock %}

{% block bodycontent %}
    <section id="welcome_post" class="col-9">
        <h2>Welcome To Mager BANK |  <span id="prof_name">{{ user }}.</span> </h2>  
        <br>   
        
        <form>
            <h3 style="font-weight: 300;">
                Pinjaman Digunakan Untuk Apa?
                <input type="text" class="form-control" id="loan_type" required>
            </h3>
            <br>
            <h3 style="font-weight: 300;">
                Masukan Uang Yang Diinginkan ($)
                <input type="number" class="form-control" id="loan_amt" required>
            </h3>
            <button class="btn btn-primary" type="button" id="loan_submit">Request loan</button>
        </form>
        
    </section>
{% endblock %}         

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#loan").addClass("current");

        $("#loan_submit").click(function() {
            var msg = "Your loan has been requested. You'll be notified if it gets approved in 24 hours. Press OK."
            
            if(
                $("#loan_type").val() =="" || 
                $("#loan_amt").val() == ""
            )
                    msg = "Error: One or more of the required fields is missing";
                
            
            alert(msg);
        });
    </script>
{% endblock %}

website/website/profiles/templates/profiles/profile_base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Mager Bank | Profile</title>
        
        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <!-- STYLINGS -->
        <link rel="stylesheet" href="/static/common-styles.css">
        
        {% block headcontent %}
        {% endblock %}
        
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-secondary">
            <img src="{%static "image/home.png" %}" width="45px">
            <a class="navbar-brand" href="{% url 'home' %}">&nbsp;Mager Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <form action="/akuns/logout/" method="POST">
                        {% csrf_token %}
                        <button>Logout</button>
                    </form>
                </div>
            </div>
        </nav>
        
        <br> <br> <br>
       
        <div class="container-fluid row">
        
                <!--SIDE PANEL BEGINS -->
                <section id="side_panel" class="col-3 bg-dark">
                    <img src="{%static "image/logo_02.png" %}" class="container btn">
                    <!-- OPERATIONS -->
                    <a href="{% url 'profiles:account_status' %}" class="current side" id="status">Akun Status</a> <br> <br>
                    
                    <a href="{% url 'profiles:money_transfer' %}" class="side" id="transfer">Transfer Uang</a> <br> <br>
                    
                    <a href="{% url 'profiles:loan_app' %}" class="side" id="loan">Pinjaman</a> <br> <br>
                    
                    <a href="{% url 'profiles:settings' %}" class="side" id="settings">Identitas Bank</a> <br> <br>
                    
                    <a href="{% url 'profiles:edit_details' %}" class="side warning" id="details">Edit Akun</a> <br> <br>
                    
                    <a href="{% url 'profiles:delete_account' %}" class="side danger" id="delete">Hapus Akun</a> <br> <br>                
                </section>
                <!-- SIDE PANEL ENDS -->
        
                {% block bodycontent %}
                {% endblock %}

            </div>
       
        <!-- FOOTER -->
        <section class="foot bg-secondary text-white">
            <div class="text-center">
                &copy; Website created with by <a href="https://github.com/VerzFR/Tugas-Besar-PBO" target="_blank">KelompokMager</a>    
                <br>
                <i></i><a>&copy; Hargai Hasil Dari Kerja Keras Kami</a>
            </div>
        </section>   
        
        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        {% block scriptcontent %}
        {% endblock %}
    </body>
</html>

website/website/templates/index.html
{% extends 'base_layout.html' %}
{%load static%}

{% block stylecontent %}
    <style>
        h1 {
            border-bottom: 1px solid;
        }
        h4 {
            font-weight: 400;
        }
        a:hover {
            text-decoration: none;
        }
        
        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }
    </style>
{% endblock %}
        

{% block bodycontent %}    
    
    <br>
    
    <div class="container">
        <a href="{% url 'akuns:signup' %}"><button class="btn btn-primary btn-block" id="acc"><i class="fa fa-user"></i> Create new account</button></a>
        <br> 
        <a href="{% url 'akuns:signin' %}"><button class="btn btn-primary btn-block" id="sign_in"><i class="fa fa-sign-in"></i> Sign in</button></a>
    </div>
    
    <br>
{% endblock %}